import Head from "next/head";
import Link from "next/link";
import WebsiteContainer from "../components/WebsiteContainer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS-API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WebsiteContainer>
        <div className="mt-s20 font-quaternary">
          <h1 className="text-subtitle1">API</h1>
          <div className="mt-s20 underline">
            <Link href="/weather">
              <a>WeatherAPI</a>
            </Link>
          </div>
        </div>
      </WebsiteContainer>
    </div>
  );
}
