import Head from "next/head";
import React from "react";
import Weather from "../components/Weather";

function WeatherPage() {
  return (
    <div>
      <Head>
        <title>WeatherAPI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Weather />
    </div>
  );
}

export default WeatherPage;
